services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/
      BACKEND_ORIGIN: http://localhost:3001
      FRONTEND_ORIGIN: http://localhost:3000

    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://backend:3001/api/v1
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mongo-data:
